repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-docstring-first
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: no-commit-to-branch
      args: [--branch, main]
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
    args: ["--ignore-missing-imports"]
    files: "({{cookiecutter.project_slug}})"

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.0
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/jorisroovers/gitlint
  rev: v0.18.0
  hooks:
    - id: gitlint
    - id: gitlint-ci

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.3
  hooks:
    - id: nbqa-black
    - id: nbqa-pyupgrade
      args: [--py39-plus]
    - id: nbqa-isort
      args: ['--profile=black']
    - id: nbqa-flake8
